# A list of enabled plugins (or extensions) in server
EnabledPlugins = []

# Server domain names (e.g. example.com)
ServerDomains = []

# Path to directory with plugin assemblies
PluginsDirPath = ""

# ID of this server in terms of Cadmium federation network. WARNING! This ID should be maximally unique.
ServerID = ""

# Websocket server settings
[Websocket]
    Host = "localhost"
    Port = 8000
    Endpoint = ""

# Here you can specify settings that is exposed by plugins
# For example - [Plugins.HelloWorld] is the settings for plugin called HelloWorld
[Plugins]
    [Plugins.HelloWorld]
    text = "123"
        [Plugins.HelloWorld.Test]
        modes = ["abc"]
